### ISSUE TITLE
SyntaxError: expected path separator ([)

### ISSUE THREAD

**Issue by zopyx** [dstufft/pypi-show-urls#1]
bin/pypi-show-urls  -p zopyx.smartprintng.client
# Download candidates for zopyx.smartprintng.client

Traceback (most recent call last):
  File "bin/pypi-show-urls", line 8, in <module>
    load_entry_point('pypi-show-urls==2.1.1', 'console_scripts', 'pypi-show-urls')()
  File "/private/tmp/lib/python2.6/site-packages/pypi_show_urls/**main**.py", line 148, in main
    html.findall(".//a[@rel='download']"),
  File "/opt/python_buildout/parts/opt/lib/python2.6/xml/etree/ElementPath.py", line 198, in findall
    return _compile(path).findall(element)
  File "/opt/python_buildout/parts/opt/lib/python2.6/xml/etree/ElementPath.py", line 176, in _compile
    p = Path(path)
  File "/opt/python_buildout/parts/opt/lib/python2.6/xml/etree/ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)

**Comment by dstufft** [comment]
Seems to work for me? Tried it with Python2.6 since it appears that is what you're using.

``` bash
$ pypi-show-urls -p zopyx.smartprintng.client

Download candidates for zopyx.smartprintng.client
=================================================
  19 Candiates from https://pypi.python.org/simple/zopyx.smartprintng.client/
  0 versions only available externally
```

**Comment by zopyx** [comment]
sucmac:tmp ajung$ bin/python
Python 2.6.7 (r267:88850, Aug  1 2011, 19:20:02) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by dstufft** [comment]
Hmm, what's that `r267:88850` stuff? Is yours compiled manually from a source checkout?

``` bash
$ python2.6
Python 2.6.8 (unknown, Sep 15 2012, 18:31:12)
[GCC 4.2.1 Compatible Apple Clang 4.0 ((tags/Apple/clang-421.0.60))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by zopyx** [comment]
Works with Python 2.7 but not with 2.6

**Comment by Themanwithoutaplan** [comment]
FWIW this is a restriction in Python 2.6's ElementTree.

```
from xml.etree.ElementTree import Element
tree = Element("root")
tree.find("me[id='a']")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/etree/ElementTree.py", line 330, in find
    return ElementPath.find(self, path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/etree/ElementPath.py", line 186, in find
    return _compile(path).find(element)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/etree/ElementPath.py", line 176, in _compile
    p = Path(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/etree/ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)
```
